export const PROGRESS_MAX_TO_ZERO_DELAY = 1000;

export const INIT_FINISHED_PROGRESS = 20;

export const FETCH_PROFILE_FINISHED_PROGRESS = 30;

export const FETCH_REPOS_FINISHED_PROGRESS = 30;

export const LOAD_HEATMAP_FINISHED_PROGRESS = 20;
